apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: e-commerce-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-commerce-frontend
  template:
    metadata:
      labels:
        app: e-commerce-frontend
    spec:
      containers:
        - name: frontend-container
          image: youracrname.azurecr.io/frontend-app:$(Build.BuildId)
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: e-commerce-frontend
